get:
  tags:
    - Productos
  summary: Obtener un producto por ID
  parameters:
    - name: id
      in: path
      description: ID del producto
      required: true
      schema:
        type: integer
  responses:
    '200':
      description: Exito
put:
  tags:
    - Productos
  summary: Modificar un producto
  parameters:
    - name: id
      in: path
      description: ID del producto
      required: true
      schema:
        type: integer
  responses:
    '200':
      description: Exito
delete:
  tags:
    - Productos
  summary: Borrar producto
  parameters:
    - name: id
      in: path
      description: ID del producto
      required: true
      schema:
        type: integer
  responses:
    '200':
      description: Exito
