openapi: 3.0.0
info:
  title: Delilah Resto
  version: 0.0.1
tags:
  - name: Pedidos
    description: Endpoint de pedidos
  - name: Productos
    description: Endpoint de productos
  - name: Usuarios
    description: Endpoint de acceso
paths:
  /pedidos:
    $ref: paths\pedidos.yaml
  '/pedidos/{id}':
    $ref: 'paths\pedidos@{id}.yaml'
  '/pedidos/{id}/status':
    $ref: 'paths\pedidos@{id}@status.yaml'
  /productos:
    $ref: paths\productos.yaml
  '/productos/{id}':
    $ref: 'paths\productos@{id}.yaml'
  /usuarios:
    $ref: paths\usuarios.yaml
  /usuarios/login:
    $ref: paths\usuarios@login.yaml
  /usuarios/logout:
    $ref: paths\usuarios@logout.yaml
